spring:
  application:
    name: BookingSystem

  datasource:
    url: jdbc:postgresql://localhost:5432/booking_system_db
    username: postgres
    password: Manudeep@050607
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

razorpay:
  key-id : rzp_test_TMvd30sVLuJM3f
  key-secret : DGmmrzBfYkBUki59XR6B73yi
  
server:
  port: 8080